[package]
name = "lsm-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytes = "1.10.0"
crossbeam-skiplist = "0.1.3"
parking_lot = "0.12.3"
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5.14"
